// <auto-generated />
namespace Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class std_dept_rel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(std_dept_rel));
        
        string IMigrationMetadata.Id
        {
            get { return "202011201209208_std_dept_rel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
